In [29]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [30]:
pd.set_option('display.max_columns', None)

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as RFC
# from xgboost import XGBClassifier as XGB
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.model_selection import ParameterGrid
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# 1. Train 이상치 찾아보기
- 밀려적힘
- 이상한 값이 적힘
- 객관식 보기가 아닌 다른숫자
- 중복대답


In [59]:
meta2017 = pd.read_csv('/gdrive/MyDrive/2조/data/코드정리/Data_Original/KNOW_2017.csv')
meta2018 = pd.read_csv('/gdrive/MyDrive/2조/data/코드정리/Data_Original/KNOW_2018.csv')
meta2019 = pd.read_csv('/gdrive/MyDrive/2조/data/코드정리/Data_Original/KNOW_2019.csv')
meta2020 = pd.read_csv('/gdrive/MyDrive/2조/data/코드정리/Data_Original/KNOW_2020.csv')

## 1-1. 학습에서 필요없는 knowcode 제거

In [33]:
#knowcode 결측치 제거
meta2017 = meta2017[meta2017['knowcode'] != 9999999]
meta2018 = meta2018[meta2018['knowcode'] != 9999999]
meta2019 = meta2019[meta2019['knowcode'] != 9999999]
meta2020 = meta2020[meta2020['knowcode'] != 9999999]

## 1-2. 이상치 및 결측치 찾기


컬럼별로 돌아가며 이상한 애들을 찾는다

In [34]:
for col in meta2017.columns[129:140]: #여기서 연도별로 슬라이스 해줘가며 컬럼별로 유니크값을 본다
# for col in meta2018.columns[129:140]:
# for col in meta2019.columns[129:140]:
# for col in meta2020.columns[129:140]:
  print(col)
  L = meta2017[col].unique()
  # L = meta2018[col].unique()
  # L = meta2019[col].unique()
  # L = meta2020[col].unique()
  try:
    L.sort() #값들이 순서대로 나옴 -> 가독성 좋게보려고
    if len(L) < 10:
      print(L)
    else:
      for i in range(10,len(L),10):
        print(L[i-10:i])
      print(L[i:])
      print()
    print()
  except:
    print(f'{col} 이상함 발견됨!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!') #이건 sort안되는걸 방지
    print()

# EX) 예를 들어 보기가 1~5 번부터 인데 여기서 나온 값이 [1,2,3,4,5,8, 2900] 이면 이상한 값이 껴있다고 유추가능

bq24_4
[1 2]

bq24_5
[1 2]

bq24_6
[1 2]

bq24_7
[1 2]

bq24_8
[1 2]

bq25
[1 2 3 4 5]

bq26
[1 2 3 4 5]

bq27
[1 2 3 4 5]

bq28
[1 2 3 4 5]

bq29
[1 2 3 4 5]

bq30
['(수학)선생님,(수학)교사' '(영업)사원, (판매)사원' '(영업/판매)사원' '(의사)선생님' '(체육)선생님,교사'
 '(판매)사원' '00바텐더님' '00반 선생님' '00씨, 00기사' '00씨,사장님']
['119' '119구급대원' '3D' '3D프로그래머,3D아티스트,컴퓨터브로그래머TD,그랙픽아티스트' 'A/S 기사' 'A/S기사'
 'AE' 'CG(컴퓨터 그래픽)' 'CPA' 'CPA, 공인회계사, 회계사']
['CTO' 'DJ / 아나듀오 / 아나듀서 / MC' 'Design engineer' 'Dr, 의사' 'FC' 'FC, 설계사'
 'FD' 'Fab 총괄 관리자, 장비실장, 안전관리자' 'IT서비스 헬퍼' 'MC, 사회자']
['MC,마술사,마술강사,일루셔니스트' 'NDT, NDE' 'NGO단체활동가, 단체의 감사' 'OP' 'PB'
 'PB, 자산관리사, 증권브로커, 금융상품상담사' 'PCO' 'PC엔지니어' 'PD' 'PD, 감독']
['PD, 제작가' 'PD, 프로듀서' 'PD, 프로듀서, 연출가' 'PD,감독님' 'PM' 'PR인' 'RF엔지니어' 'S.H'
 'SOC engineer, ASIC enginee, Front-End Engineer, Inplementation Engineer'
 'VTS']
['ca' 'chef' 'chef,요리사' 'color cordinator' 'operater(운전원)' '~씨' '가공기사'
 '가방디자이너' '가수' '가스안전관리사']
['가스안전관리자' '가이드' '가이드, 선생님' '가이드,선생님' '가이드님' '가이드님, 선생님' '가정부' '간병사' '간병인'
 '간판공']
['간호사' '간

## 1-3. Column 순회하면서 발견한점 정리
- 객관식답에 주관식 답이 들어가 있거나
- 주관식 답에 객관식 답이 들어가 있는걸 심심치 않게 볼 수 있다
- 이에따라 몇몇 Row 값들이 어느 부분에서 밀려 적힌곳이 있을 거라고 유추가능
- 밀려적힌 값들을 우선 찾는게 중요하다고 판단됨


성별을 묻는 질문 보기 1,2만 올 수 있다

In [35]:
meta2018['bq35'] #

0       1
1       1
2       1
3       1
4       2
       ..
9067    1
9068    1
9069    2
9070    1
9071    1
Name: bq35, Length: 9072, dtype: object

그러나 이렇게 1,2 말고 다른 값들이 있다

bq36이 나이를 주관식으로 입력하는 질문인데 거기서 밀려 적힌듯 하다

In [36]:
meta2018['bq35'].unique() 

array([1.0, 2.0, 27.0, 40.0, 31.0, 53.0, 39.0, 26.0, 32.0, 52.0, 50.0,
       42.0, 35.0, 46.0, 37.0, 25.0, 44.0, 47.0, 56.0, '1', '2',
       ' 라이트룸 등의 컴퓨터 프로그램"', '42', '33', '45', '38', '30'], dtype=object)

위에 코드에 따라 bq 36 질문이 bq35에다가 한칸 앞으로 밀려 적힌것을 알 수 있다

In [37]:
meta2018[meta2018['bq35'] == 27.0]

idx  cq1  cq2  cq3  cq4  cq5  cq6  cq7  cq8  cq9  cq10  cq11  cq12  \
456    9942    3    5    5    5    2    5    2    4    3     3     1     1   
6512  16005    2    5    5    5    5    5    5    5    5     5     4     3   

      cq13  cq14  cq15  cq16  cq17  cq18  cq19  cq20  cq21  cq22  cq23  cq24  \
456      5     5     5     4     4   4.0   4.0   5.0   4.0   4.0   4.0   2.0   
6512     5     5     1     3     4   1.0   1.0   1.0   1.0   1.0   1.0   1.0   

      cq25  cq26  cq27  cq28  cq29  cq30  cq31  cq32  cq33  cq34  cq35  cq36  \
456    5.0   2.0   5.0   3.0   3.0   2.0   4.0   2.0   2.0   5.0   5.0   5.0   
6512   1.0   1.0   1.0   3.0   3.0   2.0   2.0   2.0   5.0   5.0   5.0   5.0   

      cq37  cq38  cq39  cq40  cq41  cq42  cq43  cq44  cq45  cq46  cq47  cq48  \
456    3.0   1.0   2.0   4.0   3.0   2.0   1.0   2.0   3.0   1.0   1.0   4.0   
6512   5.0   3.0   1.0   5.0   5.0   3.0   1.0   3.0   5.0   1.0   1.0   4.0   

      cq49  cq50_1  cq50_2  cq50_3  cq50_4  cq50_5  cq50_6  cq50_7  cq50_8  \
456    1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     4.0   
6512   1.0     2.0     2.0     1.0     1.0     1.0     1.0     1.0     3.0   

      iq1  iq2  iq3  iq4  iq5  iq6  bq1  bq2  bq3   bq4 bq4_1a bq4_1b bq4_1c  \
456   3.0  1.0  4.0  2.0  5.0  4.0  2.0  6.0  1.0  전기기사                    1   
6512  4.0  3.0  3.0  4.0  3.0  3.0  1.0  3.0  2.0                          1   

     bq5             bq5_1 bq5_2  bq6  bq7  bq8_1  bq8_2  bq8_3  bq9  bq10  \
456    6          전기설비유지보수     7  2.0  4.0    4.0    4.0    4.0  3.0   4.0   
6512   2  프로그램 툴사용.제품구조 이해     5  4.0  4.0    4.0    3.0    4.0  4.0   2.0   

      bq11 bq12_1 bq12_2 bq12_3 bq12_4  bq12_5  bq13  bq14  bq15  bq16  bq17  \
456    2.0      3      5      5      4     1.0   1.0   1.0   2.0   3.0   1.0   
6512   4.0      4      4      4      3     2.0   1.0   1.0   1.0   1.0   1.0   

      bq18  bq19   bq20 bq21 bq221 bq222 bq223 bq231  bq232  bq233 bq234  \
456    1.0   4.0   80.0    1           0     1     0    0.0    0.0         
6512   2.0   4.0  100.0    1           0     1     0    0.0    0.0         

     bq235 bq241 bq242 bq243 bq244 bq245 bq25 bq25_1 bq26_1 bq26_1a bq26_2  \
456      1                             1    2      1      2       1      2   
6512           2                       1    2      1      2       1      2   

     bq26_2a bq26_3 bq26_3a bq26_4 bq26_4a  bq27                      bq28  \
456        1      2       1      1       2   2.0                       자동화   
6512       1      2       1      1       2   2.0  기술의 발전으로 적은 인원으로 일처리가 가능   

     bq28_1      bq29 bq30  bq31   bq32 bq33 bq34 bq35 bq36   bq37 bq37_1  \
456          Auto CAD         없음           3    1   27    4  전자전기학      1   
6512             프로그램       제품설계  3D프린터    3    1   27    4   기계공학      1   

     bq38 bq38_1 bq38_2 bq39    bq40 bq41_1 bq41_2 bq41_3  knowcode  
456     1             1   40  3000.0   2700           NaN    831101  
6512    1             1   52    2900   2300           NaN    821101

< 다른 발견한 점 >
1. 이렇게 밀려 적힌값을 보니 맨뒤가 Nan으로 입력되어 있다.
2. 이 설문지는 결측값이 있으면 ' '로 저장하는데, 밀려 적힌 값이 있는 Row는 저렇게 맨뒤가 Nan이 존재한다
3. Nan이 있는 Row들을 조사하면 밀려적힌 값들을 찾을 수 있을 듯 하다
4. Nan 값이 있는 Column들을 찾아 Nan이 있는 Row들을 추적한다

## 1-4. 연도별 조사

2017년 : 딱히 문제되는걸 못찾음

In [38]:
c_list = meta2017.columns.tolist()
nan2017 = []

for i in c_list:
    nan2017.append([i,list(meta2017[meta2017[i].isnull()].index)])
nan2017 #2017년에서는 발견되지 않음

[['idx', []],
 ['aq1_1', []],
 ['aq1_2', []],
 ['aq2_1', []],
 ['aq2_2', []],
 ['aq3_1', []],
 ['aq3_2', []],
 ['aq4_1', []],
 ['aq4_2', []],
 ['aq5_1', []],
 ['aq5_2', []],
 ['aq6_1', []],
 ['aq6_2', []],
 ['aq7_1', []],
 ['aq7_2', []],
 ['aq8_1', []],
 ['aq8_2', []],
 ['aq9_1', []],
 ['aq9_2', []],
 ['aq10_1', []],
 ['aq10_2', []],
 ['aq11_1', []],
 ['aq11_2', []],
 ['aq12_1', []],
 ['aq12_2', []],
 ['aq13_1', []],
 ['aq13_2', []],
 ['aq14_1', []],
 ['aq14_2', []],
 ['aq15_1', []],
 ['aq15_2', []],
 ['aq16_1', []],
 ['aq16_2', []],
 ['aq17_1', []],
 ['aq17_2', []],
 ['aq18_1', []],
 ['aq18_2', []],
 ['aq19_1', []],
 ['aq19_2', []],
 ['aq20_1', []],
 ['aq20_2', []],
 ['aq21_1', []],
 ['aq21_2', []],
 ['aq22_1', []],
 ['aq22_2', []],
 ['aq23_1', []],
 ['aq23_2', []],
 ['aq24_1', []],
 ['aq24_2', []],
 ['aq25_1', []],
 ['aq25_2', []],
 ['aq26_1', []],
 ['aq26_2', []],
 ['aq27_1', []],
 ['aq27_2', []],
 ['aq28_1', []],
 ['aq28_2', []],
 ['aq29_1', []],
 ['aq29_2', []],
 ['aq30_1', []],
 

2018년 조사 : nan 값 있는 row 발견

In [39]:
c_list = meta2018.columns.tolist()
nan2018 = []

for i in c_list:
    nan2018.append([i,list(meta2018[meta2018[i].isnull()].index)])
nan2018

[['idx', []],
 ['cq1', []],
 ['cq2', []],
 ['cq3', []],
 ['cq4', []],
 ['cq5', []],
 ['cq6', []],
 ['cq7', []],
 ['cq8', []],
 ['cq9', []],
 ['cq10', []],
 ['cq11', []],
 ['cq12', []],
 ['cq13', []],
 ['cq14', []],
 ['cq15', []],
 ['cq16', []],
 ['cq17', []],
 ['cq18', []],
 ['cq19', []],
 ['cq20', []],
 ['cq21', []],
 ['cq22', []],
 ['cq23', []],
 ['cq24', []],
 ['cq25', []],
 ['cq26', []],
 ['cq27', []],
 ['cq28', []],
 ['cq29', []],
 ['cq30', []],
 ['cq31', []],
 ['cq32', []],
 ['cq33', []],
 ['cq34', []],
 ['cq35', []],
 ['cq36', []],
 ['cq37', []],
 ['cq38', []],
 ['cq39', []],
 ['cq40', []],
 ['cq41', []],
 ['cq42', []],
 ['cq43', []],
 ['cq44', []],
 ['cq45', []],
 ['cq46', []],
 ['cq47', []],
 ['cq48', []],
 ['cq49', []],
 ['cq50_1', []],
 ['cq50_2', []],
 ['cq50_3', []],
 ['cq50_4', []],
 ['cq50_5', []],
 ['cq50_6', []],
 ['cq50_7', []],
 ['cq50_8', []],
 ['iq1', []],
 ['iq2', []],
 ['iq3', []],
 ['iq4', []],
 ['iq5', []],
 ['iq6', []],
 ['bq1', []],
 ['bq2', []],
 ['bq3', []]

각 직업군별로 값이 입력된다고 가정하고
Knowcode 별로 Nan이 있는 Row들을 모아봤다.

In [40]:
meta2018.loc[[406, 1253,1548,1628,1946,2938,3064,
              3505,4000,4076,4254,4478,4718,4884,
              5292,5433,5574,5784,5902,6094,6465,
              6512,6685,7480,7815,7920,7992,8171,
              8205,8760,8783,8987,8992,9016]]['knowcode'].value_counts()

821101    16
831101    14
562101     1
415404     1
622304     1
131201     1
Name: knowcode, dtype: int64

공교롭게도 특정 직업군에 Nan값이 몰려있는 경우가 많았다

In [41]:
meta2018[meta2018.knowcode == 821101]

idx  cq1  cq2  cq3  cq4  cq5  cq6  cq7  cq8  cq9  cq10  cq11  cq12  \
1253  10741    4    5    4    5    4    4    3    4    3     3     3     2   
1548  11036    1    1    1    1    3    3    1    2    1     1     2     1   
1628  11116    3    1    1    1    2    4    1    2    2     2     2     2   
3505  12996    2    2    1    1    2    2    2    2    2     3     2     2   
4000  13491    4    5    4    5    5    4    4    3    5     4     3     2   
4076  13568    4    5    4    5    5    4    4    3    5     4     3     2   
4718  14210    1    1    1    1    3    3    2    2    1     1     1     1   
4884  14376    2    1    1    2    4    4    4    3    5     4     3     2   
5292  14784    1    2    1    2    2    4    2    1    2     1     2     1   
5433  14925    3    5    4    5    3    3    2    2    3     3     3     2   
5902  15395    1    1    1    1    3    3    1    2    1     1     1     1   
6512  16005    2    5    5    5    5    5    5    5    5     5     4     3   
7815  17310    3    5    4    4    5    5    4    4    5     5     3     3   
7920  17415    2    5    5    5    5    4    4    4    3     3     3     3   
8760  18257    5    5    5    3    5    5    5    5    5     5     5     5   
8987  18484    1    2    1    2    2    3    2    4    4     4     3     3   

      cq13  cq14  cq15  cq16  cq17  cq18  cq19  cq20  cq21  cq22  cq23  cq24  \
1253     5     5     5     3     4   5.0   4.0   5.0   4.0   4.0   2.0   1.0   
1548     5     2     3     4     5   5.0   1.0   5.0   4.0   4.0   1.0   1.0   
1628     1     5     1     4     3   3.0   3.0   1.0   1.0   1.0   1.0   1.0   
3505     4     2     1     4     4   3.0   3.0   3.0   2.0   4.0   2.0   1.0   
4000     5     3     5     3     5   3.0   3.0   3.0   1.0   1.0   1.0   1.0   
4076     5     3     5     3     5   3.0   3.0   3.0   1.0   1.0   1.0   1.0   
4718     5     1     1     4     5   5.0   1.0   5.0   3.0   2.0   1.0   1.0   
4884     5     3     5     3     5   3.0   3.0   3.0   1.0   1.0   1.0   1.0   
5292     4     2     1     5     4   1.0   2.0   3.0   1.0   2.0   1.0   1.0   
5433     5     5     1     3     5   2.0   5.0   5.0   3.0   1.0   1.0   1.0   
5902     5     1     1     4     5   5.0   1.0   5.0   4.0   1.0   1.0   1.0   
6512     5     5     1     3     4   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
7815     5     1     1     3     3   3.0   3.0   3.0   2.0   2.0   1.0   1.0   
7920     5     2     1     3     1   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
8760     5     5     1     5     3   3.0   1.0   1.0   1.0   1.0   1.0   1.0   
8987     5     2     2     3     4   2.0   3.0   3.0   2.0   4.0   2.0   1.0   

      cq25  cq26  cq27  cq28  cq29  cq30  cq31  cq32  cq33  cq34  cq35  cq36  \
1253   1.0   1.0   3.0   3.0   3.0   2.0   3.0   1.0   3.0   5.0   3.0   3.0   
1548   5.0   5.0   5.0   2.0   3.0   3.0   3.0   2.0   5.0   5.0   4.0   3.0   
1628   2.0   3.0   3.0   2.0   2.0   2.0   4.0   4.0   5.0   5.0   2.0   2.0   
3505   4.0   3.0   2.0   2.0   4.0   2.0   3.0   2.0   5.0   4.0   4.0   3.0   
4000   1.0   2.0   2.0   3.0   3.0   1.0   1.0   1.0   5.0   1.0   4.0   2.0   
4076   1.0   2.0   2.0   3.0   2.0   1.0   1.0   1.0   5.0   1.0   4.0   2.0   
4718   5.0   5.0   5.0   1.0   4.0   3.0   3.0   3.0   5.0   5.0   4.0   3.0   
4884   1.0   2.0   2.0   5.0   2.0   1.0   2.0   1.0   5.0   1.0   4.0   2.0   
5292   3.0   4.0   2.0   1.0   5.0   1.0   2.0   3.0   5.0   5.0   3.0   2.0   
5433   4.0   1.0   5.0   2.0   4.0   1.0   3.0   2.0   5.0   5.0   4.0   3.0   
5902   5.0   5.0   5.0   1.0   4.0   3.0   3.0   3.0   5.0   5.0   4.0   4.0   
6512   1.0   1.0   1.0   3.0   3.0   2.0   2.0   2.0   5.0   5.0   5.0   5.0   
7815   2.0   1.0   1.0   2.0   2.0   2.0   3.0   2.0   2.0   3.0   4.0   4.0   
7920   1.0   1.0   1.0   3.0   3.0   2.0   2.0   2.0   5.0   5.0   4.0   3.0   
8760   1.0   1.0   2.0   2.0   3.0   3.0   2.0   2.0   3.0   2.0   4.0   4.0   
8987   3.0   3.0   2.0   2.0   4.0   2.0

1. 직업코드 821101의 경우 값이 밀려있는게 확실하나 어디부터 밀린건지는 알수가 없다
2. 설문지의 정보와 비교하여 밀린값을 유추해본다
- cp46보기 : 1,2,3,4,5
- cp47보기 : 1,2,3
- cp48보기 : 1,2
- cp49보기 : 1,2,3,4,5
- cp50_1보기 : 1,2,3

3. 현재 데이터 상황
- cp46 : 1 만있음
- cp47 : 1 만있음
- cp48 : 2보다 큰값이 있음
- cp49 : 1,3이 있음
- cp50_1 : 4보다 작은 값들임

4. 이에따라 cp49의 답변이 cp48로 밀려적혀 있음을 확실하게 알 수 있다

5. 고로 cp48을 결측으로 놔두고 모두 한칸씩 뒤로 민다

6. 이전부터 밀렸을수도 있으나 일단 확실한 지점부터 밀린값들을 옮기는 작업을 하는게 맞는다 생각했고, cp48 이전 질문이 밀려적혔더라도 같은 직업간의 개별적인 특징은 고대로 담고있는거라 집요하게 밀린시점을 찾는것을 여기서 마치자 했다

831101 도 821101 같은 양상으로 밀려있어 위와같이 밀린값을 처리하는 작업을 한다

In [42]:
meta2018[meta2018.knowcode == 831101]

idx  cq1  cq2  cq3  cq4  cq5  cq6  cq7  cq8  cq9  cq10  cq11  cq12  \
456    9942    3    5    5    5    2    5    2    4    3     3     1     1   
1946  11434    2    5    4    4    5    4    4    3    3     2     3     2   
2938  12429    1    5    4    3    3    4    4    4    4     3     3     3   
4254  13746    2    5    5    5    4    4    3    4    4     4     3     4   
4478  13970    2    4    5    5    4    5    3    3    5     4     4     4   
5574  15067    1    5    5    5    5    4    3    3    3     3     3     3   
5784  15277    3    5    5    5    5    5    4    4    5     5     1     1   
6094  15587    1    5    5    5    5    4    2    3    2     4     3     3   
6465  15958    2    5    4    4    5    4    4    4    5     4     4     3   
7480  16975    1    5    5    5    5    5    3    5    3     4     5     5   
7992  17487    1    5    5    3    5    4    5    4    3     4     4     3   
8171  17666    2    5    5    4    4    4    4    4    3     4     4     4   
8783  18280    1    5    5    5    5    4    2    3    3     3     3     3   
8992  18489    2    5    5    5    5    3    4    4    3     4     4     4   
9016  18513    4    5    4    4    4    4    4    3    4     3     2     2   

      cq13  cq14  cq15  cq16  cq17  cq18  cq19  cq20  cq21  cq22  cq23  cq24  \
456      5     5     5     4     4   4.0   4.0   5.0   4.0   4.0   4.0   2.0   
1946     5     4     1     3     4   4.0   1.0   4.0   1.0   1.0   1.0   3.0   
2938     5     3     1     3     1   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
4254     5     4     2     3     2   3.0   2.0   2.0   2.0   2.0   2.0   2.0   
4478     3     5     4     5     4   5.0   4.0   3.0   4.0   3.0   3.0   4.0   
5574     5     5     5     5     2   4.0   3.0   3.0   3.0   3.0   1.0   3.0   
5784     5     5     5     3     1   1.0   1.0   1.0   1.0   1.0   1.0   4.0   
6094     5     4     4     4     2   4.0   3.0   2.0   3.0   2.0   2.0   2.0   
6465     5     3     2     3     3   2.0   2.0   2.0   2.0   1.0   1.0   1.0   
7480     5     4     3     4     3   3.0   1.0   1.0   1.0   3.0   1.0   1.0   
7992     5     4     5     3     3   4.0   3.0   3.0   3.0   3.0   1.0   1.0   
8171     5     2     2     3     3   2.0   2.0   3.0   1.0   3.0   1.0   1.0   
8783     5     4     4     3     2   4.0   3.0   2.0   3.0   2.0   2.0   2.0   
8992     5     2     2     3     4   2.0   2.0   4.0   1.0   1.0   2.0   1.0   
9016     5     3     2     3     3   3.0   3.0   3.0   2.0   1.0   2.0   2.0   

      cq25  cq26  cq27  cq28  cq29  cq30  cq31  cq32  cq33  cq34  cq35  cq36  \
456    5.0   2.0   5.0   3.0   3.0   2.0   4.0   2.0   2.0   5.0   5.0   5.0   
1946   2.0   1.0   2.0   5.0   1.0   1.0   1.0   1.0   2.0   4.0   3.0   4.0   
2938   2.0   1.0   1.0   5.0   1.0   1.0   3.0   1.0   2.0   3.0   2.0   4.0   
4254   4.0   4.0   2.0   2.0   4.0   2.0   4.0   2.0   4.0   3.0   3.0   3.0   
4478   5.0   4.0   4.0   2.0   3.0   3.0   4.0   2.0   2.0   5.0   4.0   3.0   
5574   5.0   4.0   3.0   2.0   3.0   2.0   4.0   2.0   2.0   4.0   3.0   2.0   
5784   2.0   1.0   1.0   4.0   2.0   2.0   5.0   1.0   2.0   5.0   2.0   3.0   
6094   2.0   2.0   2.0   4.0   2.0   2.0   4.0   2.0   2.0   4.0   2.0   2.0   
6465   2.0   1.0   1.0   2.0   5.0   1.0   1.0   1.0   5.0   4.0   4.0   4.0   
7480   2.0   1.0   1.0   5.0   1.0   1.0   1.0   1.0   2.0   1.0   2.0   2.0   
7992   1.0   3.0   3.0   2.0   4.0   2.0   3.0   3.0   3.0   5.0   3.0   4.0   
8171   2.0   3.0   3.0   2.0   4.0   2.0   5.0   1.0   5.0   4.0   2.0   3.0   
8783   2.0   2.0   2.0   4.0   2.0   2.0   4.0   2.0   2.0   4.0   2.0   2.0   
8992   1.0   3.0   3.0   2.0   4.0   2.0   5.0   1.0   5.0   4.0   2.0   3.0   
9016   3.0   2.0   2.0   5.0   1.0   1.0   1.0   2.0   2.0   3.0   3.0   3.0   

      cq37  cq38  cq39  cq40  cq41  cq42  cq43  cq44  cq45  cq46  cq47  cq48  \
456    3.0   1.0   2.0   4.0   3.0   2.0   1.0   2.0   3.0   1.0   1.0   4.0   
1946   3.0   2.0   3.0   4.0   4.0   

562101 결측치 안보임

In [43]:
meta2018[meta2018.knowcode == 562101]

idx  cq1  cq2  cq3  cq4  cq5  cq6  cq7  cq8  cq9  cq10  cq11  cq12  \
120    9606    3    1    4    1    3    5    2    4    3     2     2     4   
185    9671    3    1    3    1    1    2    3    4    4     1     1     3   
406    9892    5    3    5    2    2    4    4    5    3     1     2     3   
465    9951    3    1    4    1    3    5    3    3    2     2     2     4   
701   10187    4    3    5    3    3    5    4    4    4     2     3     3   
886   10373    4    2    4    1    4    3    2    3    1     2     2     4   
1146  10634    3    1    4    1    3    5    2    4    2     2     2     3   
1338  10826    5    1    5    1    2    5    4    4    4     1     1     5   
1424  10912    3    3    3    2    2    3    3    3    3     3     3     3   
1474  10962    4    1    4    1    3    5    2    3    2     2     2     3   
2392  11882    4    1    4    1    3    5    2    3    2     2     2     4   
4752  14244    3    1    4    1    3    5    3    4    3     2     2     4   
4817  14309    4    1    4    1    3    5    2    4    2     1     2     4   
5299  14791    3    1    5    1    3    5    2    3    2     2     2     3   
6674  16168    3    4    5    3    3    4    4    4    4     4     4     5   

      cq13  cq14  cq15  cq16  cq17  cq18  cq19  cq20  cq21  cq22  cq23  cq24  \
120      4     1     5     1     1   2.0   3.0   1.0   1.0   4.0   1.0   1.0   
185      3     3     3     1     1   1.0   3.0   1.0   3.0   3.0   1.0   3.0   
406      3     4     5     1     3   2.0   3.0   2.0   1.0   1.0   1.0   1.0   
465      3     1     5     1     1   3.0   3.0   1.0   1.0   4.0   1.0   1.0   
701      3     2     5     1     3   2.0   2.0   2.0   1.0   1.0   1.0   1.0   
886      3     3     5     1     1   2.0   5.0   1.0   4.0   4.0   1.0   3.0   
1146     3     1     5     1     1   1.0   3.0   1.0   1.0   4.0   1.0   1.0   
1338     5     2     5     1     4   5.0   5.0   3.0   5.0   1.0   1.0   3.0   
1424     3     3     3     3     3   3.0   3.0   3.0   3.0   3.0   1.0   2.0   
1474     3     1     5     1     3   3.0   3.0   1.0   1.0   4.0   1.0   1.0   
2392     4     1     5     1     3   3.0   3.0   1.0   1.0   4.0   1.0   1.0   
4752     4     1     5     1     3   1.0   3.0   1.0   2.0   3.0   1.0   1.0   
4817     4     1     5     1     3   3.0   4.0   1.0   1.0   4.0   1.0   1.0   
5299     3     1     5     1     1   1.0   3.0   1.0   1.0   4.0   1.0   1.0   
6674     3     4     3     5     2   1.0   1.0   1.0   1.0   1.0   2.0   1.0   

      cq25  cq26  cq27  cq28  cq29  cq30  cq31  cq32  cq33  cq34  cq35  cq36  \
120    1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   3.0   2.0   1.0   2.0   
185    1.0   1.0   3.0   1.0   2.0   2.0   4.0   5.0   2.0   5.0   1.0   2.0   
406    1.0   2.0   2.0   2.0   2.0   3.0   3.0   3.0   3.0   4.0   3.0   2.0   
465    1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   3.0   5.0   1.0   2.0   
701    1.0   2.0   2.0   2.0   2.0   3.0   3.0   4.0   4.0   4.0   2.0   2.0   
886    1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   2.0   3.0   1.0   3.0   
1146   1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   3.0   3.0   1.0   2.0   
1338   1.0   1.0   1.0   1.0   1.0   3.0   3.0   1.0   2.0   5.0   1.0   5.0   
1424   3.0   2.0   1.0   1.0   1.0   3.0   3.0   3.0   3.0   5.0   1.0   1.0   
1474   1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   4.0   2.0   1.0   2.0   
2392   1.0   1.0   1.0   2.0   1.0   3.0   3.0   5.0   2.0   5.0   1.0   2.0   
4752   1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   4.0   4.0   1.0   2.0   
4817   1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   2.0   5.0   1.0   2.0   
5299   1.0   1.0   1.0   1.0   1.0   3.0   3.0   5.0   3.0   3.0   1.0   2.0   
6674   1.0   1.0   1.0   2.0   3.0   2.0   3.0   1.0   1.0   3.0   2.0   2.0   

      cq37  cq38  cq39  cq40  cq41  cq42  cq43  cq44  cq45  cq46  cq47  cq48  \
120    2.0   2.0   2.0   2.0   3.0   3.0   2.0   2.0   1.0   3.0   1.0   1.0   
185    2.0   3.0   2.0   2.0   5.0   

KnowCode: 415404
- Index 3064 : bq14부터 오른쪽 한칸이동
- Index 8551 : bq33부터 오른쪽 한칸이동

In [44]:
meta2018[meta2018.knowcode == 415404]

idx  cq1  cq2  cq3  cq4  cq5  cq6  cq7  cq8  cq9  cq10  cq11  cq12  \
1420  10908    4    2    4    5    3    4    5    4    4     4     5     3   
1468  10956    4    4    4    4    4    4    4    4    4     3     3     3   
1658  11146    5    3    3    3    3    3    4    3    4     1     2     3   
1807  11295    4    3    4    5    2    3    4    1    3     2     2     2   
2271  11761    5    3    5    5    5    5    4    4    4     3     3     4   
2347  11837    5    3    5    5    5    5    5    5    5     2     3     5   
2685  12175    3    3    5    5    3    5    2    5    4     1     3     3   
2810  12301    5    3    5    5    5    5    4    4    4     1     3     2   
2896  12387    5    3    5    5    5    5    4    2    3     1     3     3   
3064  12555    5    1    5    5    5    5    5    5    5     3     5     3   
3095  12586    5    4    5    5    5    5    5    5    5     2     3     4   
3144  12635    4    2    5    5    4    5    4    4    4     3     5     4   
3164  12655    5    4    4    5    3    4    4    4    4     3     4     2   
3271  12762    5    3    5    5    5    5    5    5    5     3     4     3   
3572  13063    4    3    4    5    5    5    4    3    4     4     4     3   
3590  13081    4    3    4    5    4    4    4    3    4     3     5     3   
3619  13110    4    2    5    5    4    5    3    5    3     3     3     3   
3852  13343    5    1    5    5    5    5    4    4    3     1     3     3   
3887  13378    4    3    4    5    4    4    4    5    4     4     4     4   
4165  13657    4    2    4    5    3    4    5    5    5     1     3     3   
4426  13918    4    2    5    5    4    4    5    4    5     4     5     3   
4602  14094    4    3    4    5    4    4    5    4    4     2     2     2   
4729  14221    5    3    4    5    5    4    4    4    5     4     4     3   
4833  14325    4    1    5    5    5    4    4    5    3     2     4     3   
4886  14378    5    3    4    4    3    4    3    3    4     2     4     3   
4953  14445    4    2    5    5    4    4    4    3    3     1     4     3   
5001  14493    4    2    5    5    3    5    4    4    3     2     3     3   
5166  14658    5    4    4    5    5    5    4    5    4     4     4     4   
5358  14850    4    4    4    4    4    4    4    4    4     3     3     3   
5532  15025    3    4    4    4    4    4    5    3    4     4     5     4   
5589  15082    4    2    5    5    5    4    4    4    4     4     4     2   
5761  15254    5    2    5    5    4    5    5    5    5     1     5     4   
5986  15479    5    5    5    5    5    5    5    5    5     5     5     4   
6061  15554    5    3    4    5    3    4    4    3    4     3     3     3   
6666  16160    5    3    5    5    4    5    5    5    4     4     5     4   
7342  16836    5    3    5    5    5    5    4    5    3     2     3     3   
7502  16997    5    4    5    3    3    5    4    5    5     3     4     2   
7595  17090    4    3    3    4    4    3    3    4    4     3     4     2   
7732  17227    5    1    5    5    5    5    4    4    4     3     3     3   
8429  17925    4    4    4    5    4    5    4    4    3     2     3     4   
8518  18015    4    2    4    5    5    5    4    2    3     1     3     3   
8551  18048    5    4    3    3    1    5    2    2    1     1     2     2   
8579  18076    3    1    3    3    3    3    5    1    5     1     3     1   
8696  18193    5    3    5    5    4    5    4    4    4     1     4     3   
8948  18445    4    2    4    4    4    5    5    4    2     3     3     3   

      cq13  cq14  cq15  cq16  cq17  cq18  cq19  cq20  cq21  cq22  cq23  cq24  \
1420     3     4     3     4     3   3.0   3.0   1.0   1.0   1.0   1.0   1.0   
1468     3     4     4     4     3   3.0   2.0   3.0   1.0   2.0   1.0   1.0   
1658     3     5     1     1     3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
1807     2     5     2     1     3   2.0   2.0   1.0   2.0   1.0   1.0   1.0   
2271     2     5   

Knowcode : 622304

Index 8205 : bq30부터 오른쪽으로 4칸 이동후 bq30~33은 결측으로 둠

In [45]:
meta2018[meta2018.knowcode == 622304]

idx  cq1  cq2  cq3  cq4  cq5  cq6  cq7  cq8  cq9  cq10  cq11  cq12  \
330    9816    5    1    5    1    1    4    1    4    1     1     1     2   
532   10018    5    1    5    1    1    5    4    1    1     3     4     1   
715   10201    3    2    5    1    1    3    1    2    2     1     1     1   
925   10413    5    1    4    2    2    4    4    4    4     1     2     1   
958   10446    5    1    3    1    1    5    2    4    4     3     3     3   
1209  10697    5    1    4    1    1    4    4    4    3     1     1     2   
1291  10779    4    1    3    1    1    3    3    3    1     1     1     2   
1358  10846    3    1    4    1    2    4    1    4    2     1     1     2   
1372  10860    5    1    5    1    2    3    2    2    2     2     1     2   
1442  10930    5    1    4    1    1    3    3    1    1     3     3     2   
1488  10976    5    2    5    2    5    5    3    3    4     5     4     4   
1497  10985    5    1    1    1    1    2    1    3    3     2     1     3   
1652  11140    4    1    4    1    1    5    4    4    2     1     1     1   
1757  11245    5    1    5    1    1    5    1    3    3     1     1     2   
1792  11280    5    1    5    1    1    5    1    4    2     1     1     2   
2316  11806    5    1    5    1    4    2    1    4    1     1     1     3   
2345  11835    5    2    5    2    4    4    3    4    3     3     3     2   
2488  11978    5    1    5    1    1    5    1    4    2     1     1     2   
3573  13064    4    1    4    1    2    4    1    4    1     1     1     3   
3686  13177    5    1    5    1    3    5    4    4    3     4     4     5   
3960  13451    5    1    5    1    1    5    4    3    1     1     1     1   
4127  13619    4    2    5    3    1    2    2    4    1     1     3     1   
4498  13990    2    1    5    1    2    4    1    4    1     1     1     2   
4663  14155    5    1    5    3    1    5    3    3    3     1     1     3   
4904  14396    5    3    3    1    1    5    3    4    3     5     4     2   
4910  14402    5    1    4    1    1    3    3    1    1     3     3     2   
5038  14530    1    1    5    1    1    2    1    1    1     1     1     2   
5262  14754    4    1    5    1    1    5    4    4    4     1     1     2   
5353  14845    5    1    5    1    1    2    4    4    1     1     1     1   
5903  15396    4    1    5    1    2    4    1    4    2     1     4     2   
5905  15398    4    1    5    1    1    4    4    4    4     1     1     2   
6043  15536    4    1    5    1    1    4    4    4    2     1     1     2   
6276  15769    5    1    4    1    1    3    3    1    1     3     3     2   
6345  15838    3    1    4    2    2    4    3    3    3     1     1     1   
6808  16302    5    1    5    1    1    4    4    3    3     2     4     3   
6894  16388    5    1    5    1    1    5    4    1    1     4     4     1   
7050  16544    4    1    1    1    1    4    2    2    2     2     2     4   
7341  16835    5    1    5    1    1    5    4    3    1     1     1     1   
7393  16888    5    1    5    1    1    5    4    1    1     3     3     1   
7453  16948    5    1    5    1    1    4    3    4    3     2     4     3   
7844  17339    4    1    4    1    1    5    5    5    4     1     1     1   
8053  17548    2    1    5    1    1    2    1    2    1     1     1     2   
8205  17700    1    1    5    1    5    3    3    3    3     1     1     1   
8596  18093    5    1    4    1    1    3    3    1    1     3     3     2   
8797  18294    4    1    5    1    2    2    1    4    1     1     4     2   

      cq13  cq14  cq15  cq16  cq17  cq18  cq19  cq20  cq21  cq22  cq23  cq24  \
330      3     1     5     5     4   3.0   2.0   1.0   2.0   4.0   2.0   1.0   
532      1     1     5     5     1   1.0   1.0   1.0   5.0   1.0   1.0   1.0   
715      3     1     4     5     1   2.0   3.0   1.0   4.0   1.0   1.0   1.0   
925      1     1     5     1     3   3.0   1.0   1.0   1.0   1.0   1.0   1.0   
958      1     2   

Knowcode : 131201

Index 8205 : bq33부터 오른쪽으로 한칸씩

In [46]:
meta2018[meta2018.knowcode == 131201]

idx  cq1  cq2  cq3  cq4  cq5  cq6  cq7  cq8  cq9  cq10  cq11  cq12  \
552   10038    5    2    3    3    2    2    5    3    2     1     3     2   
556   10042    4    4    4    4    4    2    3    3    4     4     4     3   
762   10248    5    3    5    5    4    5    3    3    3     2     2     4   
855   10342    5    3    3    3    3    2    5    3    2     1     2     3   
2247  11737    4    1    5    5    5    5    3    4    3     2     2     2   
2589  12079    5    1    3    3    3    3    5    3    2     2     2     3   
3340  12831    4    4    4    5    3    4    4    3    4     2     3     2   
5535  15028    4    4    4    4    4    2    3    3    4     4     4     3   
5955  15448    5    4    5    5    2    5    4    5    5     5     5     3   
6295  15788    4    4    4    4    4    2    3    3    4     4     4     3   
6685  16179    2    1    3    4    4    5    4    4    3     1     3     2   
7385  16880    4    3    4    4    4    4    4    4    4     3     4     2   
7638  17133    5    4    5    5    5    5    5    5    4     4     4     3   
8327  17822    2    2    4    3    3    2    3    3    3     4     4     2   
8975  18472    5    3    5    5    4    4    4    3    4     4     5     3   

      cq13  cq14  cq15  cq16  cq17  cq18  cq19  cq20  cq21  cq22  cq23  cq24  \
552      2     5     1     1     3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
556      1     5     1     1     3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
762      3     5     3     4     3   4.0   4.0   2.0   2.0   2.0   2.0   4.0   
855      2     5     1     1     3   1.0   1.0   1.0   1.0   1.0   3.0   1.0   
2247     2     5     4     4     3   4.0   4.0   4.0   4.0   3.0   1.0   1.0   
2589     3     5     3     3     3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
3340     3     5     2     1     3   2.0   1.0   1.0   1.0   1.0   1.0   1.0   
5535     1     5     1     1     3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
5955     2     5     3     2     4   2.0   2.0   2.0   2.0   1.0   1.0   1.0   
6295     1     5     1     1     3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   
6685     2     5     4     4     3   2.0   2.0   2.0   2.0   2.0   2.0   1.0   
7385     2     5     2     1     3   2.0   1.0   1.0   1.0   2.0   1.0   1.0   
7638     3     5     5     5     4   4.0   5.0   3.0   2.0   4.0   2.0   2.0   
8327     2     3     3     3     2   2.0   2.0   2.0   1.0   2.0   1.0   1.0   
8975     3     4     4     5     3   3.0   4.0   4.0   4.0   3.0   2.0   2.0   

      cq25  cq26  cq27  cq28  cq29  cq30  cq31  cq32  cq33  cq34  cq35  cq36  \
552    1.0   1.0   1.0   1.0   3.0   3.0   1.0   3.0   1.0   3.0   3.0   3.0   
556    1.0   1.0   1.0   1.0   5.0   1.0   1.0   1.0   1.0   2.0   1.0   5.0   
762    2.0   2.0   2.0   2.0   5.0   2.0   1.0   2.0   2.0   2.0   3.0   1.0   
855    1.0   1.0   2.0   2.0   3.0   3.0   2.0   3.0   2.0   3.0   4.0   3.0   
2247   4.0   1.0   1.0   1.0   5.0   2.0   1.0   2.0   2.0   2.0   3.0   2.0   
2589   1.0   1.0   3.0   1.0   3.0   3.0   2.0   3.0   2.0   3.0   4.0   4.0   
3340   1.0   2.0   1.0   1.0   4.0   2.0   1.0   1.0   1.0   4.0   1.0   4.0   
5535   1.0   1.0   1.0   1.0   5.0   1.0   1.0   1.0   1.0   2.0   1.0   5.0   
5955   1.0   1.0   1.0   2.0   5.0   1.0   1.0   5.0   1.0   2.0   2.0   2.0   
6295   1.0   1.0   1.0   1.0   5.0   1.0   1.0   1.0   1.0   2.0   1.0   5.0   
6685   2.0   3.0   1.0   1.0   2.0   4.0   2.0   2.0   1.0   2.0   2.0   3.0   
7385   1.0   1.0   1.0   1.0   4.0   2.0   1.0   1.0   1.0   4.0   1.0   3.0   
7638   2.0   2.0   1.0   2.0   4.0   2.0   2.0   3.0   2.0   3.0   3.0   4.0   
8327   1.0   2.0   1.0   1.0   3.0   3.0   2.0   3.0   2.0   3.0   3.0   3.0   
8975   1.0   3.0   1.0   1.0   3.0   3.0   2.0   1.0   1.0   2.0   4.0   4.0   

      cq37  cq38  cq39  cq40  cq41  cq42  cq43  cq44  cq45  cq46  cq47  cq48  \
552    2.0   2.0   1.0   3.0   4.0   3.0   2.0   1.0   3.0   2.0   1.0   1.0   
556    5.0   4.0   1.0   4.0   5.0   

2019년 : 2018년과 같은 방식으로 진행

In [47]:
c_list = meta2019.columns.tolist()
nan2019 = []

for i in c_list:
    nan2019.append([i,list(meta2019[meta2019[i].isnull()].index)])
nan2019

[['idx', []],
 ['sq1', []],
 ['sq2', []],
 ['sq3', []],
 ['sq4', []],
 ['sq5', []],
 ['sq6', []],
 ['sq7', []],
 ['sq8', []],
 ['sq9', []],
 ['sq10', []],
 ['sq11', []],
 ['sq12', []],
 ['sq13', []],
 ['sq14', []],
 ['sq15', []],
 ['sq16', []],
 ['kq1_1', []],
 ['kq1_2', []],
 ['kq2_1', []],
 ['kq2_2', []],
 ['kq3_1', []],
 ['kq3_2', []],
 ['kq4_1', []],
 ['kq4_2', []],
 ['kq5_1', []],
 ['kq5_2', []],
 ['kq6_1', []],
 ['kq6_2', []],
 ['kq7_1', []],
 ['kq7_2', []],
 ['kq8_1', []],
 ['kq8_2', []],
 ['kq9_1', []],
 ['kq9_2', []],
 ['kq10_1', []],
 ['kq10_2', []],
 ['kq11_1', []],
 ['kq11_2', []],
 ['kq12_1', []],
 ['kq12_2', []],
 ['kq13_1', []],
 ['kq13_2', []],
 ['kq14_1', []],
 ['kq14_2', []],
 ['kq15_1', []],
 ['kq15_2', []],
 ['kq16_1', []],
 ['kq16_2', []],
 ['kq17_1', []],
 ['kq17_2', []],
 ['kq18_1', []],
 ['kq18_2', []],
 ['kq19_1', []],
 ['kq19_2', []],
 ['kq20_1', []],
 ['kq20_2', []],
 ['kq21_1', []],
 ['kq21_2', []],
 ['kq22_1', []],
 ['kq22_2', []],
 ['kq23_1', []],
 ['kq23_

Nan 값 있는 컬럼들

In [48]:
meta2019.loc[[177, 614, 1394, 2610, 2687, 3309, 3361, 7251, 7758]]['knowcode'].value_counts()

13902     2
414303    1
158501    1
134303    1
415503    1
413202    1
132002    1
151201    1
Name: knowcode, dtype: int64

Knowcode : 13902

Index 1394 : bq6과 bq7을 bq20_1로 밀어냄
bq8부터 bq21로 밀어냄

In [49]:
meta2019[meta2019.knowcode == 13902]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
43    18612    4    4    4    4    4    3    4    3    5     4     4     3   
127   18696    4    5    5    3    5    5    3    5    5     5     5     5   
262   18831    5    4    5    5    4    4    4    4    4     4     5     4   
634   19203    4    5    4    5    4    4    4    5    5     4     5     5   
748   19317    4    4    5    4    4    5    3    4    3     4     5     5   
1394  19963    3    4    4    4    5    4    5    5    5     4     5     5   
4213  22783    4    4    5    4    3    4    5    4    5     4     5     3   
4569  23140    5    4    5    5    4    5    4    4    4     4     5     3   
4632  23203    5    5    5    4    5    4    5    5    5     5     5     5   
4877  23448    4    5    5    4    5    4    5    4    4     4     5     4   
7104  25676    5    5    5    5    4    4    3    3    4     5     4     3   
7568  26140    4    4    4    4    4    4    4    4    4     4     4     3   
7688  26260    4    3    3    3    3    3    4    3    4     3     4     4   
7758  26330    5    5    5    5    4    2    3    5    5     4     5     4   
7897  26469    5    5    5    5    5    5    5    5    5     5     5     4   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
43       4     3     3     4      3      4      2      3      3      5      3   
127      5     5     5     5      3      4      3      4      3      4      3   
262      4     4     5     5      5      6      3      3      4      5      5   
634      5     4     5     5      2      2      2      4      1      0      2   
748      4     3     3     5      4      4      5      5      2      3      3   
1394     3     4     3     4      3      4      3      4      3      4      4   
4213     5     3     4     5      3      4      3      5      3      4      4   
4569     5     5     4     3      5      5      4      5      4      5      4   
4632     5     4     5     5      3      3      5      5      2      2      4   
4877     5     3     3     4      3      4      4      3      2      3      2   
7104     3     2     3     5      3      4      5      6      2      3      5   
7568     4     3     3     3      2      4      2      5      3      3      4   
7688     3     4     3     4      4      4      4      4      3      4      4   
7758     3     2     3     5      3      4      3      2      3      4      5   
7897     4     5     4     5      5      5      4      6      4      5      5   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
43        5      3      5      2      5      1      0      1      0      3   
127       5      5      5      3      5      1      0      1      0      2   
262       5      5      5      5      5      1      0      1      0      3   
634       4      4      6      2      4      1      0      1      0      1   
748       4      4      5      3      4      2      3      1      0      4   
1394      6      3      5      3      5      2      3      1      0      2   
4213      6      4      5      4      5      2      4      1      0      3   
4569      5      4      5      3      5      1      0      1      0      2   
4632      5      5      5      3      4      1      0      1      0      5   
4877      4      3      4      3      5      1      0      1      0      1   
7104      5      5      5      3      5      3      4      1      0      4   
7568      5      4      5      4      5      4      5      1      0      4   
7688      5      4      4      3      5      2      3      1      0      3   
7758      7      5      5      2      4      2      4      1      0      3   
7897      6      5      7      5      5      1      0      1      0      4   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
43        5       1       0       4       6       1       0       1       0   
127       4       1       0       2       3       1    

Knowcode : 13902

Index 7758 : bq20부터 한 칸 뒤로

In [50]:
meta2019[meta2019.knowcode == 414303]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
1065  19634    3    4    4    2    4    4    3    3    4     4     3     4   
1141  19710    3    3    3    3    3    3    3    3    3     3     3     3   
1333  19902    4    5    5    5    5    5    5    4    5     5     4     4   
1350  19919    2    4    4    3    4    3    4    3    5     3     3     4   
1675  20245    4    3    3    3    5    3    3    4    4     3     3     4   
2002  20572    4    4    3    2    4    5    3    4    4     5     5     5   
2079  20649    4    5    4    3    4    2    2    5    5     5     5     5   
2687  21257    3    2    2    3    3    2    3    2    2     3     3     2   
3912  22482    5    4    5    3    5    4    3    4    4     5     5     4   
4426  22997    4    4    4    2    3    2    3    2    3     3     3     4   
4672  23243    4    5    4    1    2    2    1    3    4     3     2     2   
5481  24052    4    4    4    3    5    5    4    3    4     4     4     5   
6191  24762    5    4    4    4    4    3    4    4    4     4     4     4   
6235  24806    5    5    4    3    4    4    4    4    4     3     3     5   
6480  25051    3    3    3    3    4    4    2    4    4     4     3     3   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
1065     2     3     4     3      1      0      3      3      1      0      2   
1141     3     3     3     3      2      3      2      3      2      3      2   
1333     4     3     5     3      3      4      2      4      1      0      5   
1350     2     2     1     2      2      4      2      5      2      3      1   
1675     3     3     2     3      2      2      2      2      2      2      2   
2002     4     3     4     5      3      1      3      3      1      0      2   
2079     4     5     4     3      1      0      1      0      1      0      1   
2687     2     2     3     3      1      0      1      0      1      0      1   
3912     4     4     3     3      3      4      3      4      3      4      5   
4426     4     4     3     2      2      3      2      3      2      2      2   
4672     1     1     1     1      1      0      1      0      1      0      1   
5481     2     2     3     4      1      0      2      2      1      0      1   
6191     3     2     4     4      3      4      2      4      2      3      4   
6235     3     4     5     4      1      0      1      0      1      0      3   
6480     3     3     3     3      1      0      2      2      1      0      1   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
1065      4      3      3      1      0      1      0      2      3      2   
1141      3      2      3      2      3      2      3      2      3      2   
1333      6      3      4      2      4      1      0      1      0      4   
1350      0      1      0      1      0      1      0      1      0      3   
1675      2      2      2      1      0      2      2      1      0      1   
2002      1      2      2      1      0      1      0      1      0      4   
2079      0      1      0      1      0      1      0      1      0      2   
2687      0      1      0      1      0      1      0      1      0      2   
3912      5      5      5      4      5      2      2      2      1      5   
4426      2      2      2      2      2      1      0      1      0      2   
4672      0      1      0      1      0      1      0      1      0      1   
5481      0      1      0      1      0      1      0      1      0      3   
6191      6      5      4      2      4      1      0      1      0      4   
6235      3      3      1      1      0      1      0      1      0      1   
6480      0      1      0      2      1      1      0      1      0      2   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
1065      3       1       0       4       6       2       3       1       0   
1141      3       2       3       3       4       2    

Knowcode : 158501

Index 3361 : bq21_3부터 한 칸씩 오른쪽으로

In [51]:
meta2019[meta2019.knowcode == 158501]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
408   18977    5    5    5    5    5    5    5    5    4     4     4     5   
466   19035    4    4    4    4    4    4    4    3    3     4     5     5   
1719  20289    3    4    3    1    4    3    4    5    4     4     3     4   
1783  20353    3    3    3    3    4    4    4    4    4     3     3     3   
3118  21688    4    4    5    5    5    4    5    5    4     4     5     5   
3231  21801    4    4    5    5    4    4    4    5    4     5     4     5   
3361  21931    4    3    3    3    3    3    3    4    3     3     4     4   
3910  22480    4    3    4    3    3    3    3    3    3     2     3     3   
4280  22850    3    4    4    2    5    5    2    4    4     4     5     4   
4983  23554    5    4    4    4    5    5    4    4    5     4     5     5   
5282  23853    5    5    5    3    5    5    3    5    5     5     5     5   
6448  25019    5    5    5    5    5    5    5    5    5     4     5     5   
7306  25878    4    3    4    4    4    3    4    2    2     3     5     4   
7653  26225    4    3    2    4    3    2    3    3    3     4     5     4   
7917  26489    3    3    3    3    3    3    3    3    3     3     3     3   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
408      4     4     4     5      4      4      3      5      4      4      4   
466      5     3     3     5      5      4      4      5      3      5      5   
1719     3     3     4     3      1      0      3      5      1      0      1   
1783     4     4     4     4      1      0      4      4      1      0      1   
3118     5     5     5     4      3      4      4      2      3      5      3   
3231     4     4     4     5      4      3      4      4      4      3      4   
3361     4     3     4     4      1      0      1      0      1      0      1   
3910     4     3     2     2      1      0      2      3      1      0      1   
4280     4     4     5     5      1      0      3      3      2      2      3   
4983     5     2     3     5      1      0      4      6      1      0      1   
5282     2     5     4     5      1      0      4      3      1      0      5   
6448     5     5     5     5      1      0      3      3      1      0      1   
7306     3     2     3     3      3      1      3      3      4      2      3   
7653     4     2     3     3      1      0      3      2      1      0      2   
7917     3     3     3     3      3      4      3      4      3      4      3   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
408       5      4      4      3      5      3      4      3      4      3   
466       5      4      5      4      4      4      3      2      2      3   
1719      0      2      3      1      0      1      0      1      0      4   
1783      0      3      4      1      0      1      0      1      0      3   
3118      4      5      4      1      0      1      0      1      0      4   
3231      4      4      4      4      4      1      0      1      0      4   
3361      0      1      0      1      0      1      0      1      0      4   
3910      0      2      3      1      0      1      0      1      0      2   
4280      3      4      5      4      4      3      3      1      0      2   
4983      0      1      0      1      0      1      0      1      0      2   
5282      4      3      4      1      0      3      4      1      0      3   
6448      0      1      0      1      0      1      0      1      0      3   
7306      2      3      2      3      1      3      1      3      1      3   
7653      1      3      2      1      0      3      2      1      0      3   
7917      4      3      4      3      4      3      4      3      4      3   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
408       4       4       6       3       3       3       5       3       4   
466       5       4       4       2       5       4    

Knowcode : 134303

Index 3361 : bq20부터 한 칸씩 오른쪽으로

In [52]:
meta2019[meta2019.knowcode == 134303]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
1883  20453    5    5    5    5    5    5    5    5    3     3     3     4   
2430  21000    2    2    2    1    1    1    2    2    2     3     2     2   
3050  21620    2    2    2    1    2    1    2    2    3     2     2     2   
4288  22859    2    3    4    4    3    2    4    4    4     4     4     4   
4437  23008    4    3    4    3    4    2    3    3    3     4     4     4   
5398  23969    2    2    2    1    1    1    2    2    2     2     2     2   
5870  24441    3    2    2    1    2    1    2    1    2     3     2     3   
6091  24662    2    2    2    1    1    1    2    1    2     2     2     2   
6223  24794    4    4    4    5    4    4    4    4    4     4     4     5   
6343  24914    5    5    5    5    5    5    5    5    4     4     5     5   
6495  25066    5    5    5    5    5    5    5    5    5     5     5     5   
6984  25556    3    3    3    3    4    4    3    3    3     3     5     5   
7251  25823    5    4    5    1    4    4    4    5    4     4     5     5   
7338  25910    2    2    3    1    1    1    3    2    2     2     2     3   
7860  26432    3    2    2    2    4    4    4    3    5     5     5     2   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
1883     5     3     3     3      3      4      4      6      4      5      4   
2430     1     1     1     2      1      0      3      4      1      0      1   
3050     2     1     1     2      1      0      1      0      1      0      1   
4288     2     4     4     4      3      4      3      2      3      3      4   
4437     4     3     2     3      2      3      3      4      2      3      2   
5398     1     1     1     2      1      0      3      4      1      0      1   
5870     1     1     1     2      1      0      2      3      1      0      2   
6091     1     1     1     2      1      0      3      4      1      0      1   
6223     4     3     3     4      2      2      3      4      1      0      1   
6343     5     4     5     5      5      4      5      5      3      4      1   
6495     5     5     5     5      2      2      5      6      1      0      1   
6984     3     2     2     3      2      2      3      6      3      3      2   
7251     5     2     5     5      2      2      2      2      2      2      4   
7338     2     1     1     3      1      0      3      4      1      0      1   
7860     2     1     1     2      1      0      3      4      1      0      1   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
1883      5      4      5      2      3      4      5      4      5      4   
2430      0      2      3      1      0      1      0      1      0      4   
3050      0      1      0      1      0      1      0      1      0      4   
4288      3      4      6      2      2      1      0      1      0      1   
4437      3      4      5      1      0      1      0      1      0      3   
5398      0      3      4      1      0      1      0      1      0      3   
5870      3      2      3      1      0      1      0      1      0      4   
6091      0      3      4      1      0      1      0      1      0      4   
6223      0      4      5      2      4      1      0      1      0      5   
6343      0      4      5      3      5      1      0      1      0      5   
6495      0      1      0      1      0      1      0      1      0      5   
6984      2      2      2      2      2      1      0      1      0      1   
7251      5      5      6      3      4      2      2      1      0      5   
7338      0      3      4      1      0      1      0      1      0      3   
7860      0      3      5      1      0      1      0      1      0      4   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
1883      6       4       5       4       5       4       5       3       4   
2430      4       2       3       1       0       1    

Knowcode : 415503

Index 3361 : bq24부터 한 칸씩 뒤로

In [53]:
meta2019[meta2019.knowcode == 415503]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
452   19021    3    3    3    4    4    4    3    3    4     4     3     2   
886   19455    5    4    5    5    4    4    3    4    3     3     4     4   
1637  20207    5    5    5    4    4    3    3    4    5     5     5     5   
1656  20226    3    3    4    3    4    3    3    3    3     4     5     3   
3022  21592    4    4    4    3    4    3    4    4    4     4     4     5   
3309  21879    5    4    5    5    5    4    5    5    4     5     5     5   
3516  22086    5    5    5    2    3    3    2    4    5     5     4     4   
3725  22295    3    4    4    4    5    4    5    4    5     5     5     5   
4658  23229    3    4    3    2    5    4    4    4    3     5     4     5   
4681  23252    4    4    4    3    3    3    2    3    5     4     3     4   
6502  25073    5    4    4    3    4    3    3    5    5     5     3     4   
6810  25382    3    3    4    2    4    3    3    4    3     3     3     4   
7435  26007    4    3    4    3    3    2    3    3    3     4     4     5   
7855  26427    3    3    3    4    3    3    4    5    4     4     4     5   
8136  26708    5    4    5    3    5    5    4    4    4     5     5     5   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
452      2     3     3     3      1      0      1      0      1      0      1   
886      4     2     4     3      3      4      3      3      2      4      2   
1637     3     4     5     3      5      4      3      5      4      4      5   
1656     3     2     3     2      2      2      3      2      2      3      2   
3022     3     4     5     3      2      3      2      3      2      2      2   
3309     4     3     3     5      2      1      3      3      1      0      1   
3516     2     5     2     3      1      0      4      3      1      0      1   
3725     4     3     4     3      1      0      4      4      1      0      2   
4658     3     4     5     4      2      1      2      2      1      0      2   
4681     2     4     2     4      1      0      2      3      2      3      2   
6502     3     4     5     5      1      0      2      4      1      0      3   
6810     4     3     4     3      4      4      3      4      2      2      2   
7435     2     2     3     1      1      0      1      0      1      0      1   
7855     5     3     5     5      2      4      1      0      1      0      2   
8136     5     4     4     4      1      0      2      2      1      0      1   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
452       0      3      4      1      0      1      0      1      0      3   
886       3      2      3      4      5      1      0      1      0      4   
1637      4      4      3      5      5      4      4      1      0      3   
1656      2      2      2      2      2      1      0      1      0      2   
3022      3      3      3      2      2      2      3      1      0      2   
3309      0      1      0      1      0      1      0      1      0      3   
3516      0      1      0      1      0      1      0      1      0      3   
3725      3      4      4      3      3      1      0      1      0      4   
4658      1      2      2      3      3      1      0      1      0      2   
4681      4      1      0      2      4      2      2      1      0      3   
6502      6      1      0      1      0      1      0      1      0      4   
6810      3      3      5      2      3      3      4      1      0      4   
7435      0      1      0      1      0      1      0      1      0      2   
7855      2      1      0      1      0      1      0      1      0      3   
8136      0      1      0      1      0      1      0      1      0      4   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
452       4       3       4       3       4       1       0       3       5   
886       5       2       3       5       6       2    

Knowcode : 413202

Index 3361 : bq6에서 bq24로 이동


In [54]:
meta2019[meta2019.knowcode == 413202]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
534   19103    3    3    3    3    3    3    4    4    4     4     4     4   
1465  20034    3    3    3    3    3    3    3    3    3     3     3     3   
1693  20263    5    5    5    5    5    5    5    5    4     5     5     5   
1824  20394    4    4    5    4    5    4    5    4    3     4     5     5   
2610  21180    5    5    5    2    5    2    5    3    3     2     5     5   
3378  21948    4    4    4    2    4    3    4    3    3     3     4     4   
3911  22481    4    4    5    1    4    2    3    3    4     3     4     4   
4048  22618    4    5    5    5    5    5    5    5    5     5     5     5   
4986  23557    3    4    5    3    4    4    3    4    4     4     5     4   
5008  23579    4    4    4    3    4    3    4    3    4     3     3     3   
5712  24283    2    2    2    2    2    2    2    2    2     2     2     2   
6372  24943    4    4    4    4    5    5    5    3    4     5     4     5   
7323  25895    3    5    5    5    5    5    5    5    5     5     5     5   
7732  26304    4    4    4    2    4    3    4    4    4     3     4     5   
7925  26497    3    2    3    2    3    3    4    3    3     3     3     4   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
534      4     4     4     4      4      5      4      6      3      4      3   
1465     3     3     3     3      4      4      3      4      3      4      3   
1693     5     4     5     5      3      4      3      4      3      4      3   
1824     5     2     2     3      4      5      5      7      1      0      1   
2610     5     5     2     3      2      4      4      6      1      0      2   
3378     4     2     2     3      1      0      3      2      1      0      1   
3911     4     2     1     2      1      0      2      3      1      0      1   
4048     5     5     5     5      3      4      4      5      3      4      5   
4986     3     4     3     4      4      4      4      5      2      3      2   
5008     4     3     3     3      3      4      3      6      3      3      3   
5712     2     2     2     2      2      2      2      2      2      2      2   
6372     4     2     3     3      5      3      5      5      2      4      2   
7323     4     5     4     4      5      4      5      5      3      2      3   
7732     4     1     2     3      1      0      4      3      1      0      1   
7925     4     3     3     4      1      0      4      5      1      0      1   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
534       4      3      4      3      4      3      4      3      4      3   
1465      4      3      4      3      4      3      4      3      4      3   
1693      4      3      4      3      2      3      4      3      4      3   
1824      0      3      4      3      4      1      0      1      0      4   
2610      2      2      3      2      2      1      0      1      0      2   
3378      0      1      0      1      0      1      0      1      0      2   
3911      0      1      0      1      0      1      0      1      0      3   
4048      6      5      5      3      5      3      3      1      0      4   
4986      2      5      4      3      4      1      0      1      0      2   
5008      5      3      4      3      4      2      2      2      1      3   
5712      2      2      2      2      2      2      2      1      0      2   
6372      3      4      4      2      4      1      0      1      0      4   
7323      4      4      5      3      4      2      2      1      0      3   
7732      0      1      0      1      0      1      0      1      0      2   
7925      0      3      4      1      0      1      0      1      0      1   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
534       4       3       4       3       4       3       3       3       2   
1465      4       3       4       3       4       3    

Knowcode : 132002

Index 614 : bq20부터 한 칸 뒤로

In [55]:
meta2019[meta2019.knowcode == 132002]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
614   19183    5    5    5    3    5    5    3    5    5     3     3     5   
673   19242    5    3    5    3    5    3    5    5    2     5     3     5   
684   19253    4    3    4    3    4    3    4    4    4     4     5     4   
848   19417    4    4    4    5    4    2    2    4    5     4     5     4   
1753  20323    3    3    4    5    4    2    4    5    5     4     5     5   
2838  21408    3    4    4    4    5    3    2    3    3     4     4     3   
3892  22462    3    3    3    4    3    3    3    3    3     3     3     4   
4332  22903    4    3    3    3    4    4    4    3    2     3     4     4   
4762  23333    5    4    5    5    4    4    4    4    4     3     4     5   
5428  23999    3    3    3    3    3    3    3    3    3     3     3     3   
7232  25804    3    4    4    4    3    3    4    3    3     3     3     4   
7408  25980    3    3    4    4    4    4    4    4    4     4     4     5   
7554  26126    4    4    4    3    5    4    4    3    5     5     5     5   
7914  26486    4    4    4    4    4    3    4    4    4     4     4     4   
8164  26736    3    4    3    2    5    4    3    3    4     3     4     3   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
614      3     3     5     5      1      0      1      0      2      2      1   
673      5     4     5     5      2      1      2      3      1      0      1   
684      5     3     3     4      1      0      2      3      1      0      1   
848      5     2     3     5      1      0      3      5      1      0      1   
1753     5     4     3     5      4      4      5      5      3      5      2   
2838     4     2     2     2      3      2      2      5      2      5      3   
3892     3     2     2     3      3      4      2      4      2      4      2   
4332     4     4     3     4      3      2      3      4      1      0      1   
4762     4     4     3     5      3      4      4      6      4      6      3   
5428     3     3     3     3      3      4      3      5      3      4      3   
7232     4     2     4     4      1      0      3      4      3      3      1   
7408     4     4     5     5      4      4      2      5      3      5      3   
7554     5     4     5     5      1      0      2      2      1      0      1   
7914     5     3     3     3      2      1      3      4      2      3      1   
8164     3     4     1     3      2      2      2      3      2      3      1   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
614       0      3      4      2      4      1      0      1      0      4   
673       0      3      4      1      0      1      0      1      0      5   
684       0      1      0      1      0      1      0      1      0      3   
848       0      3      5      1      0      1      0      1      0      3   
1753      5      4      4      2      5      4      5      2      2      5   
2838      4      4      6      1      0      3      5      2      3      4   
3892      3      3      3      2      3      2      3      1      0      3   
4332      0      3      3      2      3      2      3      1      0      4   
4762      4      3      4      3      4      3      4      3      4      5   
5428      4      3      4      3      4      1      0      1      0      3   
7232      0      1      0      1      0      1      0      1      0      3   
7408      4      3      4      3      5      5      5      1      0      5   
7554      0      3      4      2      1      1      0      1      0      5   
7914      0      1      0      1      0      1      0      1      0      3   
8164      0      1      0      3      4      1      0      1      0      4   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
614       6       3       4       3       5       1       0       3       4   
673       6       1       0       1       0       1    

Knowcode : 158501

Index 177 : bq20~bq21-3을 한 칸씩 오른쪽으로
bq24부터 한 칸씩 뒤로

In [56]:
meta2019[meta2019.knowcode == 151201]

idx  sq1  sq2  sq3  sq4  sq5  sq6  sq7  sq8  sq9  sq10  sq11  sq12  \
153   18722    5    5    5    3    5    5    5    5    5     5     5     5   
169   18738    4    2    4    3    4    4    4    4    4     4     4     4   
177   18746    5    5    5    5    5    5    5    5    5     5     5     5   
370   18939    4    3    4    3    4    4    4    3    3     4     4     4   
524   19093    3    3    3    3    4    4    4    4    4     4     4     4   
590   19159    3    4    4    4    5    5    5    4    4     4     4     3   
2290  20860    3    4    4    2    2    2    2    4    4     4     5     5   
4556  23127    4    3    4    3    4    3    5    3    3     3     4     4   
4868  23439    3    5    4    2    4    3    1    5    5     2     5     5   
5209  23780    4    3    4    4    4    4    4    4    3     3     4     4   
5333  23904    4    4    4    4    5    5    4    4    3     4     4     4   
5367  23938    4    5    4    5    5    5    4    4    4     4     4     5   
6788  25360    4    4    4    4    4    2    3    3    4     4     4     5   
8015  26587    5    5    5    4    5    5    4    5    5     5     5     5   
8437  27009    5    5    5    5    5    4    4    4    4     4     4     4   

      sq13  sq14  sq15  sq16  kq1_1  kq1_2  kq2_1  kq2_2  kq3_1  kq3_2  kq4_1  \
153      5     5     5     5      3      4      5      5      2      2      5   
169      4     3     4     4      3      4      4      3      2      3      1   
177      5     5     5     5      4      4      3      4      3      4      3   
370      4     3     5     5      3      4      3      5      3      5      3   
524      4     4     4     4      3      4      3      4      3      3      3   
590      5     3     5     4      3      4      4      4      4      5      3   
2290     3     2     2     5      2      5      2      4      2      4      2   
4556     3     3     3     3      3      4      3      5      3      5      3   
4868     5     5     5     5      1      0      3      5      1      0      1   
5209     4     2     3     4      2      2      2      2      2      2      2   
5333     4     3     5     5      3      4      3      4      3      3      3   
5367     5     5     4     5      2      3      2      3      2      3      2   
6788     4     4     5     4      2      3      3      4      3      4      4   
8015     5     4     4     5      2      3      3      3      3      4      3   
8437     4     4     4     4      2      3      1      0      1      0      1   

      kq4_2  kq5_1  kq5_2  kq6_1  kq6_2  kq7_1  kq7_2  kq8_1  kq8_2  kq9_1  \
153       6      2      2      1      0      4      3      1      0      5   
169       0      4      2      1      0      4      4      1      0      3   
177       3      3      3      3      3      3      3      3      3      3   
370       5      3      4      3      5      3      5      3      4      4   
524       4      3      4      3      4      3      4      1      0      4   
590       6      4      5      4      5      5      7      3      4      5   
2290      6      2      4      4      5      2      4      1      0      5   
4556      4      3      4      2      3      2      3      1      0      3   
4868      0      1      0      1      0      5      1      1      0      5   
5209      2      3      5      1      0      3      4      1      0      3   
5333      3      3      4      3      3      3      3      1      0      4   
5367      5      3      4      4      6      4      6      1      0      5   
6788      4      4      4      2      5      5      4      1      0      5   
8015      4      5      6      3      4      2      3      1      0      5   
8437      0      1      0      1      0      1      0      1      0      3   

      kq9_2  kq10_1  kq10_2  kq11_1  kq11_2  kq12_1  kq12_2  kq13_1  kq13_2  \
153       6       5       7       5       7       1       0       5       7   
169       4       4       6       3       5       1    

2020년도 진행

In [57]:
c_list = meta2020.columns.tolist()
nan2020 = []

for i in c_list:
    nan2020.append([i,list(meta2020[meta2020[i].isnull()].index)])
nan2020

[['idx', []],
 ['saq1_1', []],
 ['saq1_2', []],
 ['saq2_1', []],
 ['saq2_2', []],
 ['saq3_1', []],
 ['saq3_2', []],
 ['saq4_1', []],
 ['saq4_2', []],
 ['saq5_1', []],
 ['saq5_2', []],
 ['saq6_1', []],
 ['saq6_2', []],
 ['saq7_1', []],
 ['saq7_2', []],
 ['saq8_1', []],
 ['saq8_2', []],
 ['saq9_1', []],
 ['saq9_2', []],
 ['saq10_1', []],
 ['saq10_2', []],
 ['saq11_1', []],
 ['saq11_2', []],
 ['saq12_1', []],
 ['saq12_2', []],
 ['saq13_1', []],
 ['saq13_2', []],
 ['saq14_1', []],
 ['saq14_2', []],
 ['saq15_1', []],
 ['saq15_2', []],
 ['saq16_1', []],
 ['saq16_2', []],
 ['saq17_1', []],
 ['saq17_2', []],
 ['saq18_1', []],
 ['saq18_2', []],
 ['saq19_1', []],
 ['saq19_2', []],
 ['saq20_1', []],
 ['saq20_2', []],
 ['saq21_1', []],
 ['saq21_2', []],
 ['saq22_1', []],
 ['saq22_2', []],
 ['saq23_1', []],
 ['saq23_2', []],
 ['saq24_1', []],
 ['saq24_2', []],
 ['saq25_1', []],
 ['saq25_2', []],
 ['saq26_1', []],
 ['saq26_2', []],
 ['saq27_1', []],
 ['saq27_2', []],
 ['saq28_1', []],
 ['saq28_2', [

중간에 Nan 있는 컬럼이 있으나
원래 결측 들어가야할곳이 결측처리된거라
따로 진행 안하고 감

##1-5. 이상치 처리
- 위에 해당되는 이상치들은 설문지.xlsx에 저장
- 파이썬으로 직접하기엔 번거로운게 많고 수작업으로 하는게 이상적이라 수작업으로 진행